name: GetIssueBody
on:
  issues:
    types:
      - opened
      - edited
jobs:
  test1:
    runs-on: ubuntu-20.04
    steps:
      - id: step01
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: json
          script: |
            return github.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
      - id: step02
        env:
          ISSUE_DATA: ${{ toJson(steps.step01.outputs.result.data) }}
        run: echo $ISSUE_DATA
      - id: step03
        env:
          ISSUE_TITLE: ${{ toJson(steps.step01.outputs.result.data.title) }}
        run: echo $ISSUE_TITLE
      - id: step04
        env:
          ISSUE_USER: ${{ toJson(steps.step01.outputs.result.data.user) }}
        run: echo $ISSUE_USER
      - id: step05
        env:
          ISSUE_LABELS: ${{ toJson(steps.step01.outputs.result.data.labels) }}
        run: echo $ISSUE_LABELS
      - id: step06
        env:
          ISSUE_BODY: ${{ toJson(steps.step01.outputs.result.data.body) }}
        run: echo $ISSUE_BODY
