name: GetIssueBody
on:
  issues:
    types:
      - opened
      - edited
jobs:
  test1:
    runs-on: ubuntu-20.04
    steps:
      - id: step01
        uses: actions/github-script@v3
        with:
          debug: true
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: json
          script: |
            console.log(github.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            }))
      - run: echo ${{steps.step01.outputs.result}}
